[[AbstractTrees]]
deps = ["Compat"]
git-tree-sha1 = "988a9597d99936407ca41e349be519e2fef1d63d"
uuid = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
version = "0.1.0"

[[ArgParse]]
deps = ["Compat", "TextWrap"]
git-tree-sha1 = "1a80df0cdf46bd70a00b25d2e13b904515eb3ee0"
uuid = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
version = "0.5.0"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinDeps]]
deps = ["Compat", "Libdl", "SHA", "URIParser"]
git-tree-sha1 = "160d5d926e83e0970dd549ad9fe0ac3e8107e83c"
uuid = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
version = "0.8.8"

[[BinaryProvider]]
deps = ["Compat", "Libdl", "SHA"]
git-tree-sha1 = "9b40439f35dd21b87a559fccb2833377fc56517d"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.3.0"

[[BufferedStreams]]
deps = ["Compat", "Pkg", "Test"]
git-tree-sha1 = "260922227fa4affdce57c59063fabf33a324d50e"
uuid = "e1450e63-4bb3-523b-b2a4-4ffa8c0fd77d"
version = "0.4.0"

[[CategoricalArrays]]
deps = ["Compat", "JSON", "Missings", "Printf", "Reexport"]
git-tree-sha1 = "8ff661f67c4dd799626bfd4fdf6241923c792af5"
uuid = "324d7699-5711-5eae-9e2f-1d82baa6b597"
version = "0.3.9"

[[CodecZlib]]
deps = ["BinaryProvider", "Compat", "Test", "TranscodingStreams"]
git-tree-sha1 = "82742ef572290f566c6fc6d977d87586a0d3d5f1"
uuid = "944b1d66-785c-5afd-91f1-9de20f533193"
version = "0.4.3"

[[Codecs]]
deps = ["Compat"]
git-tree-sha1 = "511ccd52570f94e45022ef9698146722d4f1f94d"
uuid = "19ecbf4d-ef7c-5e4b-b54a-0a0ff23c5aed"
version = "0.4.0"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "IterativeEigensolvers", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "SuiteSparse", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "4049fa166ff47bf2b9190eb4be0de478088fe0c9"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "0.68.0"

[[Crayons]]
deps = ["Test"]
git-tree-sha1 = "f5b1135d8517fdb77ed220ac2d26ab92f2c269ca"
uuid = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
version = "0.4.1"

[[DataFrames]]
deps = ["CategoricalArrays", "CodecZlib", "Compat", "DataStreams", "Missings", "Reexport", "SortingAlgorithms", "StatsBase", "TranscodingStreams", "WeakRefStrings"]
git-tree-sha1 = "be4d979564837fbb6be9eb4872ab7352bbc32e71"
uuid = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
version = "0.11.6"

[[DataStreams]]
deps = ["Compat", "Missings", "NamedTuples", "WeakRefStrings"]
git-tree-sha1 = "62d1a39a3e9634eceb7413151b48cbc95521a059"
uuid = "9a8bc11e-79be-5b39-94d7-1ccc349a1a85"
version = "0.3.6"

[[DataStructures]]
deps = ["Compat", "REPL"]
git-tree-sha1 = "abc05631fbe6e6a62c60f37bf644df87d5470fe4"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.8.3"

[[DataValues]]
git-tree-sha1 = "cffe917847d2fea0a47bff0401a155616329802e"
uuid = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
version = "0.3.3"

[[DateParser]]
deps = ["TimeZones"]
git-tree-sha1 = "ba05c12c1fa2496f78760a62da0d67d29035d9e2"
uuid = "c513aa4d-7626-5656-a882-4604be010eff"
version = "0.1.1"

[[Dates]]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Distributed]]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[EzXML]]
deps = ["BinaryProvider", "Compat", "Test"]
git-tree-sha1 = "10d97f3fc8a8ea08e4d982f7eeed7fd305bc5b61"
uuid = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
version = "0.6.3"

[[Faker]]
deps = ["Dates", "Nettle"]
git-tree-sha1 = "38c02bd0918669d751270a99f36326399985f2c7"
uuid = "0efc519c-db33-5916-ab87-703215c3906f"
version = "0.0.3"

[[FileWatching]]
uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"

[[Gumbo]]
deps = ["AbstractTrees", "BinDeps", "Libdl"]
git-tree-sha1 = "198f3910fac5cc3e503c1c66c07c4850ac849a4e"
uuid = "708ec375-b3d6-5a57-a7ce-8257bf98657a"
version = "0.4.0"

[[HTTP]]
deps = ["Base64", "Dates", "Distributed", "IniFile", "MbedTLS", "Sockets", "Test"]
git-tree-sha1 = "f1dd8a2e46970b318e2637aed47a21af033e3998"
uuid = "cd3eb016-35fb-5094-929b-558a96fad6f3"
version = "0.6.12"

[[HTTPClient]]
deps = ["Compat", "LibCURL"]
git-tree-sha1 = "161d5776ae8e585ac0b8c20fb81f17ab755b3671"
uuid = "0862f596-cf2d-50af-8ef4-f2be67dfa83f"
version = "0.2.1"

[[Homebrew]]
deps = ["BinDeps", "Compat", "JSON", "Libdl", "Unicode"]
git-tree-sha1 = "3e6d20b90cab32759f38639e2f085b4e5aa17f21"
uuid = "d9be37ee-ecc9-5288-90f1-b9ca67657a75"
version = "0.6.3"

[[HttpCommon]]
deps = ["Compat", "Nullables", "URIParser"]
git-tree-sha1 = "aea6d6227ba9c33f7a51dcf7a7d2403b58abd439"
uuid = "77172c1b-203f-54ac-aa54-3f1198fe9f90"
version = "0.4.0"

[[HttpParser]]
deps = ["BinDeps", "Compat", "HttpCommon", "Libdl"]
git-tree-sha1 = "725d36e975b26e26a28f1bd9112948479e69841b"
uuid = "38bc9a14-d65a-5c5a-8a51-c6e7361b5ffc"
version = "0.3.1"

[[HttpServer]]
deps = ["Compat", "HttpCommon", "HttpParser", "MbedTLS"]
git-tree-sha1 = "0f7c8b3c2be0dceb7423dc4485817c8137423e89"
uuid = "58cfbd8c-6b7d-5447-85c1-563540e28d27"
version = "0.3.1"

[[IniFile]]
deps = ["Compat"]
git-tree-sha1 = "b86089c325a4287f7fc0a8240cbe2d591b1455c5"
uuid = "83e8ac13-25f8-5344-8a64-a9f2b223428f"
version = "0.4.0"

[[InteractiveUtils]]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[IterableTables]]
deps = ["DataValues", "NamedTuples", "Requires", "TableTraits"]
git-tree-sha1 = "7348432a3283225a466eaa397914c02c61eca2fb"
uuid = "1c8ee90f-4401-5389-894e-7a04a3dc0f4d"
version = "0.7.1"

[[IterativeEigensolvers]]
uuid = "de555fa4-b82f-55e7-8b71-53f60bbc027d"

[[IteratorInterfaceExtensions]]
git-tree-sha1 = "e437723cb0518b66d6b08870d2ee5ba205d3ee3e"
uuid = "82899510-4779-5014-852e-03e436cf321d"
version = "0.0.2"

[[JSON]]
deps = ["Compat", "Nullables", "Sockets", "Unicode"]
git-tree-sha1 = "e2f6776e8bfd310b2ade13fba1faf99d8967d58f"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.17.2"

[[LibCURL]]
deps = ["BinDeps", "Compat", "Libdl", "WinRPM"]
git-tree-sha1 = "9b431bc66757ad5124f4d206c319996a2dfa2662"
uuid = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"
version = "0.2.2"

[[LibExpat]]
deps = ["Compat"]
git-tree-sha1 = "8ba2ca1635ec1755bcf1432c9a2aa6c91a3fb4fd"
uuid = "522f3ed2-3f36-55e3-b6df-e94fee9b0c07"
version = "0.4.2"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[Libz]]
deps = ["BufferedStreams", "Compat"]
git-tree-sha1 = "501a8a5b0c500c3a04adb65a3468e3de5ad4e0d9"
uuid = "2ec943e9-cfe8-584d-b93d-64dcb6d567b7"
version = "0.2.4"

[[LinearAlgebra]]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Lumberjack]]
deps = ["Compat", "JSON", "Mocking", "StackTraces"]
git-tree-sha1 = "f1a2279ff2d20133958feab65ca953e75a207caf"
uuid = "ff7a09a4-2bbe-5ce1-96cb-a4b0cacc22b1"
version = "2.1.1"

[[Markdown]]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[MbedTLS]]
deps = ["BinaryProvider", "Compat", "Sockets"]
git-tree-sha1 = "08997c97ca92924bc459b675ac3cfec1b0a3385c"
uuid = "739be429-bea8-5141-9913-cc70e7f3736d"
version = "0.5.11"

[[Millboard]]
git-tree-sha1 = "d29c5529173c6f7a9716740d2fa262c56c181159"
uuid = "39ec1447-df44-5f4c-beaa-866f30b4d3b2"
version = "0.1.0"

[[Missings]]
deps = ["Compat"]
git-tree-sha1 = "4b7feda2672b8163c95738533671afb4493b6d03"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "0.2.9"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[Mocking]]
deps = ["Compat", "Dates", "Test"]
git-tree-sha1 = "6d2ad935d657319a2ac4dc60539bf5465a918068"
uuid = "78c3b35d-d492-501b-9361-3d52fe80e533"
version = "0.5.2"

[[NamedTuples]]
git-tree-sha1 = "6374851ad4b15f2a20ac20637d38c550531fa684"
uuid = "73a701b4-84e1-5df0-88ff-1968ee2ee8dc"
version = "4.0.2"

[[Nettle]]
deps = ["BinDeps", "Compat", "Homebrew", "Libdl", "WinRPM"]
git-tree-sha1 = "77e89762d1b57b7b7cefd109a5a8d7c10c3ebe2e"
uuid = "49dea1ee-f6fa-5aa6-9a11-8816cee7d4b9"
version = "0.3.0"

[[Nullables]]
deps = ["Compat"]
git-tree-sha1 = "23258f849603ad4fed3ce7dbcb8c0658920fa5ef"
uuid = "4d1e1d77-625e-5b40-9113-a560ec7a8ecd"
version = "0.0.5"

[[OhMyREPL]]
deps = ["Compat", "Crayons", "Tokenize"]
git-tree-sha1 = "d267323a09ebb68d378e66b7c90703c3eeeb31d2"
uuid = "5fb14364-9ced-5910-84b2-373655c76a03"
version = "0.2.11"

[[Pkg]]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[REPL]]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Reexport]]
git-tree-sha1 = "caba582b2e9ef39b9cfff911aa13c5ca1b9a9896"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.1.0"

[[Requires]]
git-tree-sha1 = "fc07f83ee89fdec5cf08886a61271fae8d964cf9"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "0.4.3"

[[Revise]]
deps = ["Compat", "DataStructures", "Dates", "FileWatching", "Test", "Unicode"]
git-tree-sha1 = "569dd46d6c78fb59bc1744d11c32945db6789749"
uuid = "295af30f-e4ad-537b-8983-00126c2a3abe"
version = "0.3.0"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[SearchLight]]
deps = ["DataFrames", "DataStructures", "DateParser", "Dates", "Faker", "IterableTables", "JSON", "Lumberjack", "MbedTLS", "Millboard", "Reexport", "SHA", "YAML"]
repo-url = "https://github.com/essenciary/SearchLight.jl"
uuid = "6f3c2822-70e4-11e8-26e5-e941d09eb389"
version = "0.1.0+"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SortingAlgorithms]]
deps = ["Compat", "DataStructures"]
git-tree-sha1 = "748c3ad6f150b685f1582906d1f9dba8834dd6db"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "0.2.1"

[[SparseArrays]]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[StackTraces]]
git-tree-sha1 = "6d2e45507b6480790740c54203336bc668bb1f60"
uuid = "670d9266-7b14-5e98-a133-3b8c27ea9ed4"
version = "0.1.1"

[[StatsBase]]
deps = ["Compat", "DataStructures", "LinearAlgebra", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Test"]
git-tree-sha1 = "53ae4232e9f1d7ffda8c38f80437136baed595bd"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.23.0"

[[SuiteSparse]]
uuid = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[[TableTraits]]
deps = ["IteratorInterfaceExtensions", "NamedTuples"]
git-tree-sha1 = "706ad3fe890e25bcfa8651c0f6b90605d03649ce"
uuid = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
version = "0.2.0"

[[Test]]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[TextWrap]]
deps = ["Compat"]
git-tree-sha1 = "d5fe8b5fe2ccd4802c4d0d3ce646be3232a60b4b"
uuid = "b718987f-49a8-5099-9789-dcd902bef87d"
version = "0.2.0"

[[TimeZones]]
deps = ["Compat", "EzXML", "Mocking", "Nullables"]
git-tree-sha1 = "286da21e47d25304d05d1550a984347bae3737b3"
uuid = "f269a46b-ccf7-5d73-abea-4c690281aa53"
version = "0.7.1"

[[Tokenize]]
deps = ["Printf", "Test"]
git-tree-sha1 = "b3ebedc9c38793c8f0919c853aea23154288f3c2"
uuid = "0796e94c-ce3b-5d07-9a54-7f471281c624"
version = "0.5.0"

[[TranscodingStreams]]
deps = ["Compat", "Random", "Test"]
git-tree-sha1 = "497524e8b703e67caf20cc086d20235852041fe4"
uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
version = "0.5.2"

[[URIParser]]
deps = ["Compat", "Unicode"]
git-tree-sha1 = "0f9c5e2d14e03fbd00696f9394e288bdd5adacbc"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.3.1"

[[UUIDs]]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[WeakRefStrings]]
deps = ["Compat", "Missings"]
git-tree-sha1 = "bb0464e62baf3a0767340fbb51fed584159ad9b7"
uuid = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"
version = "0.4.7"

[[WebSockets]]
deps = ["Codecs", "Compat", "HttpCommon", "HttpServer", "MbedTLS"]
git-tree-sha1 = "8b1a4424a9e5f0915f50aa2225e8164ffad6eece"
uuid = "104b5d7c-a370-577a-8038-80a2059c5097"
version = "0.4.0"

[[WinRPM]]
deps = ["BinDeps", "Compat", "HTTPClient", "LibExpat", "Libdl", "Libz", "SHA", "URIParser"]
git-tree-sha1 = "43730fcfe2f4921e7cfe1c21a6fdfeabb7ee4d74"
uuid = "c17dfb99-b4f7-5aad-8812-456da1ad7187"
version = "0.3.2"

[[YAML]]
deps = ["Codecs", "Compat"]
git-tree-sha1 = "a81c4f46c19f0eb9abaa90f3112bf536c1cfa7f9"
uuid = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
version = "0.2.1"
